# -*- coding: utf-8 -*-
# Project: ForecastingStockPrice_thesis
# Created at: 22:09

__author__ = 'phuongnt18'
__email__ = 'phuongnt18@vng.com.vn'

ticket_lst = [
	{
		'ticket': 'VNI30',
		'url': 'https://www.investing.com/indices/vn-30-components',
	},
	{
		'ticket': 'HNX30',
		'url': 'https://www.investing.com/indices/hnx-30-components',
	},
]

# real-time data header xpath
REAL_TIME_HEADER_XPATH = [
	{
		'header': 'name',
		'xpath': '//*[@id="leftColumn"]/div[1]/h1',
	},
	{
		'header': 'last',
		'xpath': '//*[@id="last_last"]',
	},
	{
		'header': 'change',
		'xpath': '//*[@id="quotes_summary_current_data"]/div[1]/div[2]/div[1]/span[2]',
	},
	{
		'header': 'change_per',
		'xpath': '//*[@id="quotes_summary_current_data"]/div[1]/div[2]/div[1]/span[4]',
	},
	{
		'header': 'volume',
		'xpath': '//*[@id="quotes_summary_secondary_data"]/div/ul/li[1]/span[2]/span',
	},
	{
		'header': 'open',
		'xpath': '//*[@id="quotes_summary_secondary_data"]/div/ul/li[2]/span[2]',
	},
	{
		'header': 'day_range',
		'xpath': '//*[@id="quotes_summary_secondary_data"]/div/ul/li[3]/span[2]',
	},
]

tbody = '//*[@id="cr1"]/tbody'
COMPONENT_HEADER_DATA = [
	{
		'header': 'name',
		'xpath': tbody + '/tr/td[2]/a',
	},
	{
		'header': 'last',
		'xpath': tbody + '/tr/td[3]',
	},
	{
		'header': 'high',
		'xpath': tbody + '/tr/td[4]',
	},
	{
		'header': 'low',
		'xpath': tbody + '/tr/td[5]',
	},
	{
		'header': 'change',
		'xpath': tbody + '/tr/td[6]',
	},
	{
		'header': 'change_per',
		'xpath': tbody + '/tr/td[7]',
	},
	{
		'header': 'volume',
		'xpath': tbody + '/tr/td[8]',
	},
]

# Configure for getting historical data
AJAX_URL = 'https://www.investing.com/instruments/HistoricalDataAjax'
HIS_DATA_HEADERS = [
	{
		'name': 'VN 30',
		'ticket': 'VN 30 (VNI30)',
		'index': 'HOSE',
		'curr_id': '41064',
		'smlID': '2058618',
		'header': 'VN 30 Historical Data',
	},
	{
		'name': 'HNX 30',
		'ticket': 'HNX30',
		'index': 'HNX',
		'curr_id': '995072',
		'smlID': '2144064',
		'header': 'HNX 30 Historical Data',
	},
	# {
	# 	'name': 'Asia Commercial Bank',
	# 	'ticket': 'ACB',
	# 	'index': 'HNX 30 (HNX30)',
	# 	'curr_id': '41913',
	# 	'smlID': '1286128',
	# 	'header': 'ACB Historical Data',
	# },
	# {
	# 	'name': 'Advanced Compound Stone JSC',
	# 	'ticket': 'VCS',
	# 	'index': 'HNX 30 (HNX30)',
	# 	'curr_id': '42260',
	# 	'smlID': '1292027',
	# 	'header': 'VCS Historical Data',
	# },
	# {
	# 	'name': 'Baoviet Securities Company',
	# 	'ticket': 'BVS',
	# 	'index': 'HNX 30 (HNX30)',
	# 	'curr_id': '41942',
	# 	'smlID': '1286621',
	# 	'header': 'BVS Historical Data',
	# },
	# {
	# 	'name': 'Bim Son Cement',
	# 	'ticket': 'BCC',
	# 	'index': 'HNX 30 (HNX30)',
	# 	'curr_id': '41928',
	# 	'smlID': '1286383',
	# 	'header': 'BCC Historical Data',
	# },
	# {
	# 	'name': 'DANANG HOUSING',
	# 	'ticket': 'NDN',
	# 	'index': 'HNX 30 (HNX30)',
	# 	'curr_id': '42088',
	# 	'smlID': '1289103',
	# 	'header': 'NDN Historical Data',
	# },
	{
		'name': 'Materials Transport Cement JSC',
		'ticket': 'VTV',
		'index': 'HNX 30 (HNX30)',
		'curr_id': '42292',
		'smlID': '1292571',
		'header': 'VTV Historical Data',
	},
	{
		'name': 'Petrovietnam Southern Gas JSC',
		'ticket': 'PGS',
		'index': 'HNX 30 (HNX30)',
		'curr_id': '42109',
		'smlID': '1289460',
		'header': 'PGS Historical Data',
	},
	{
		'name': 'Cotec Construction JSC',
		'ticket': 'CTD',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958436',
		'smlID': '1793483',
		'header': 'CTD Historical Data',
	},
	{
		'name': 'DHG Pharmaceutical JSC',
		'ticket': 'DHG',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958449',
		'smlID': '1793743',
		'header': 'DHG Historical Data',
	},
	{
		'name': 'Faros Construction Corp',
		'ticket': 'ROS',
		'index': 'VN 30 (VNI30)',
		'curr_id': '987188',
		'smlID': '25082236',
		'header': 'ROS Historical Data',
	},
	{
		'name': 'FPT Corp',
		'ticket': 'FPT',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958482',
		'smlID': '1794403',
		'header': 'FPT Historical Data',
	},
	{
		'name': 'Gemadept Corp',
		'ticket': 'GMD',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958488',
		'smlID': '1794523',
		'header': 'GMD Historical Data',
	},
	{
		'name': 'Ho Chi Minh City Infrastructure Investment JSC',
		'ticket': 'CII',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958421',
		'smlID': '1793183',
		'header': 'CII Historical Data',
	},
	{
		'name': 'Ho Chi Minh City Development Joint Stock Commercial Bank',
		'ticket': 'HDB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '1057644',
		'smlID': '25968832',
		'header': 'HDB Historical Data',
	},
	{
		'name': 'Hoa Phat Group JSC',
		'ticket': 'HPG',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958514',
		'smlID': '1795043',
		'header': 'HPG Historical Data',
	},
	{
		'name': 'Masan Group Corp',
		'ticket': 'MSN',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958566',
		'smlID': '1796083',
		'header': 'MSN Historical Data',
	},
	{
		'name': 'Military Commercial Joint Stock Bank',
		'ticket': 'MBB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958561',
		'smlID': '1795983',
		'header': 'MBB Historical Data',
	},
	{
		'name': 'Mobile World Investment Corp',
		'ticket': 'MWG',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958570',
		'smlID': '1796163',
		'header': 'MWG Historical Data',
	},
	{
		'name': 'No Va Land Investment Group Corp',
		'ticket': 'NVL',
		'index': 'VN 30 (VNI30)',
		'curr_id': '994755',
		'smlID': '25209749',
		'header': 'NVL Historical Data',
	},
	{
		'name': 'PetroVietnam Fertilizer and Chemicals Corp',
		'ticket': 'DPM',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958459',
		'smlID': '1793943',
		'header': 'DPM Historical Data',
	},
	{
		'name': 'Phu Nhuan Jewelry JSC',
		'ticket': 'PNJ',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958607',
		'smlID': '1796903',
		'header': 'PNJ Historical Data',
	},
	{
		'name': 'Refrigeration Electrical Engineering Corp',
		'ticket': 'REE',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958633',
		'smlID': '1797423',
		'header': 'REE Historical Data',
	},
	{
		'name': 'Sai Gon Thuong Tin Commercial Joint Stock Bank',
		'ticket': 'STB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958676',
		'smlID': '1798283',
		'header': 'STB Historical Data',
	},
	{
		'name': 'Saigon Beer Alcohol Beverage Corp',
		'ticket': 'SAB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '994073',
		'smlID': '25200684',
		'header': 'SAB Historical Data',
	},
	{
		'name': 'Saigon Securities Incorporation',
		'ticket': 'SSI',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958674',
		'smlID': '1798243',
		'header': 'SSI Historical Data',
	},
	{
		'name': 'Vietnam Technological And Commercial Joint Stock Bank',
		'ticket': 'TCB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '1081734',
		'smlID': '27386382',
		'header': 'TCB Historical Data',
	},
	{
		'name': 'Thanh Thanh Cong Tay Ninh JSC',
		'ticket': 'SBT',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958641',
		'smlID': '1797583',
		'header': 'SBT Historical Data',
	},
	{
		'name': 'Joint Stock Commercial Bank for Foreign Trade of Vietnam',
		'ticket': 'VCB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958731',
		'smlID': '1799383',
		'header': 'VCB Historical Data',
	},
	{
		'name': 'Vietjet Aviation JSC',
		'ticket': 'VJC',
		'index': 'VN 30 (VNI30)',
		'curr_id': '997168',
		'smlID': '25229983',
		'header': 'VJC Historical Data',
	},
	{
		'name': 'Vietnam Export Import Commercial Joint Stock Bank',
		'ticket': 'EIB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958472',
		'smlID': '1794203',
		'header': 'EIB Historical Data',
	},
	{
		'name': 'Vietnam JSCmmercial Bank for Industry and Trade',
		'ticket': 'CTG',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958437',
		'smlID': '1793503',
		'header': 'CTG Historical Data',
	},
	{
		'name': 'Vietnam Prosperity Joint Stock Commercial Bank',
		'ticket': 'VPB',
		'index': 'VN 30 (VNI30)',
		'curr_id': '1043364',
		'smlID': '25808811',
		'header': 'VPB Historical Data',
	},
	{
		'name': 'Vietnam Dairy Products JSC',
		'ticket': 'VNM',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958751',
		'smlID': '1799783',
		'header': 'VNM Historical Data',
	},
	{
		'name': 'Vincom Retail JSC',
		'ticket': 'VRE',
		'index': 'VN 30 (VNI30)',
		'curr_id': '1056075',
		'smlID': '25958129',
		'header': 'VRE Historical Data',
	},
	{
		'name': 'Vingroup JSC',
		'ticket': 'VIC',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958739',
		'smlID': '1799543',
		'header': 'VIC Historical Data',
	},
	{
		'name': 'Vinhomes JSC',
		'ticket': 'VHM',
		'index': 'VN 30 (VNI30)',
		'curr_id': '1076910',
		'smlID': '26672248',
		'header': 'VHM Historical Data',
	},
	{
		'name': 'Petrovietnam Gas JSC',
		'ticket': 'GAS',
		'index': 'VN 30 (VNI30)',
		'curr_id': '958483',
		'smlID': '1794423',
		'header': 'GAS Historical Data',
	}
]
